// Datos iniciales del centro. Las coordenadas de los espacios están calcadas
// del plano en papel (plano.jpg): cada planta usa su propio sistema de
// coordenadas en píxeles, que el cliente escala al tamaño de pantalla.

export const PLANTAS = [
  { codigo: 'P2', nombre: 'Planta 2ª', orden: 3 },
  { codigo: 'P1', nombre: 'Planta 1ª', orden: 2 },
  { codigo: 'PB', nombre: 'Planta baja', orden: 1 },
];

export const FAMILIAS = [
  { codigo: 'SSC', nombre: 'Servicios Socioculturales y a la Comunidad', color: '#e8590c' },
  { codigo: 'SEA', nombre: 'Seguridad y Medio Ambiente', color: '#c2255c' },
  { codigo: 'MAM', nombre: 'Madera, Mueble y Corcho', color: '#8d5524' },
  { codigo: 'AFD', nombre: 'Actividades Físicas y Deportivas', color: '#1c7ed6' },
  { codigo: 'IMA', nombre: 'Instalación y Mantenimiento', color: '#5f3dc4' },
  { codigo: 'SAN', nombre: 'Sanidad', color: '#2b8a3e' },
  { codigo: 'INA', nombre: 'Industrias Alimentarias', color: '#e67700' },
  { codigo: 'COM', nombre: 'Comercio y Marketing', color: '#0c8599' },
  { codigo: 'HOT', nombre: 'Hostelería y Turismo', color: '#e03131' },
  { codigo: 'TIC', nombre: 'Coordinación TIC', color: '#364fc7' },
  { codigo: 'RAD', nombre: 'Radio Atlante', color: '#d6336c' },
  { codigo: 'ORI', nombre: 'Orientación', color: '#099268' },
];

// Solo las siembra la migración 1; la migración 2 las retira si nadie las usa.
// Las categorías nuevas se crean desde la aplicación al escribirlas.
export const CATEGORIAS = [
  'Mobiliario',
  'Equipos informáticos',
  'Audiovisuales',
  'Herramientas',
  'Maquinaria',
  'Material didáctico',
  'Material sanitario',
  'Equipamiento deportivo',
  'Menaje y utensilios de cocina',
  'Electrodomésticos',
  'Equipos de seguridad y emergencias',
  'Consumibles',
  'Otros',
];

// tipo: aula | taller | informatica | almacen | comun
// familias: uso habitual del espacio (orientativo; cualquier familia puede
// tener material en cualquier espacio).
export const ESPACIOS = [
  // ── Planta 2ª ──────────────────────────────────────────────────────────
  { codigo: 'P2-01', planta: 'P2', nombre: 'Ámbito 1', tipo: 'aula', color: '#9b2a73',
    grupos: '1º G.S. Coordinación de Emergencias y Protección Civil', familias: ['SEA'],
    x: 252, y: 10, w: 116, h: 153 },
  { codigo: 'P2-02', planta: 'P2', nombre: 'Seguridad 2º', tipo: 'aula', color: '#dfe8d4',
    grupos: '2º G.M. Seguridad', familias: ['SEA'],
    x: 252, y: 163, w: 116, h: 152 },
  { codigo: 'P2-03', planta: 'P2', nombre: 'Seguridad 1º / Panadería', tipo: 'aula', color: '#e8b4b0',
    grupos: '1º G.M. Seguridad\n1º G.B. Panadería y Pastelería', familias: ['SEA', 'INA'],
    x: 252, y: 315, w: 116, h: 150 },
  { codigo: 'P2-04', planta: 'P2', nombre: 'Ámbito 2', tipo: 'aula', color: '#e07b39',
    grupos: '2º G.S. Coordinación de Emergencias y Protección Civil', familias: ['SEA'],
    x: 435, y: 15, w: 110, h: 155 },
  { codigo: 'P2-05', planta: 'P2', nombre: 'Emergencias 1º / Higiene Bucodental 2º', tipo: 'aula', color: '#f2c320',
    grupos: '1º G.M. Emergencias y Protección Civil\n2º G.S. Higiene Bucodental', familias: ['SEA', 'SAN'],
    x: 435, y: 170, w: 110, h: 150 },
  { codigo: 'P2-06', planta: 'P2', nombre: 'Emergencias 2º / Cuidados Aux. 2º', tipo: 'aula', color: '#dcdce0',
    grupos: '2º G.M. Emergencias y Protección Civil\n2º G.M. Cuidados Auxiliares de Enfermería', familias: ['SEA', 'SAN'],
    x: 435, y: 320, w: 110, h: 150 },
  { codigo: 'P2-07', planta: 'P2', nombre: 'Emergencias 1º-2º / C. Emergencias 1º', tipo: 'aula', color: '#8cc07a',
    grupos: '1º 2º G.M. Emergencias y Protección Civil\n1º G.S. Coordinación de Emergencias y Protección Civil', familias: ['SEA'],
    x: 230, y: 493, w: 187, h: 110 },
  { codigo: 'P2-08', planta: 'P2', nombre: 'Animación Sociodeportiva 2º', tipo: 'aula', color: '#6a6fa8',
    grupos: '2º G.S. Animación Sociodeportiva', familias: ['AFD'],
    x: 417, y: 498, w: 166, h: 105 },

  // ── Planta 1ª ──────────────────────────────────────────────────────────
  { codigo: 'P1-01', planta: 'P1', nombre: 'Mecatrónica', tipo: 'taller', color: '#f2c320',
    grupos: '1º 2º Mecatrónica', familias: ['IMA'],
    x: 2, y: 8, w: 156, h: 150 },
  { codigo: 'P1-02', planta: 'P1', nombre: 'Electrotecnia', tipo: 'taller', color: '#f3f1e0',
    grupos: 'Electrotecnia', familias: ['IMA'],
    x: 158, y: 12, w: 215, h: 116 },
  { codigo: 'P1-03', planta: 'P1', nombre: 'Cuidados Aux. / Atención Dependencia', tipo: 'aula', color: '#f1efc0',
    grupos: '1º 2º G.M. Cuidados Auxiliares de Enfermería\n1º 2º G.M. Atención a Personas en Situación de Dependencia', familias: ['SAN', 'SSC'],
    x: 2, y: 158, w: 158, h: 154 },
  { codigo: 'P1-04', planta: 'P1', nombre: 'Higiene Bucodental 1º', tipo: 'aula', color: '#f4c28f',
    grupos: '1º G.S. Higiene Bucodental', familias: ['SAN'],
    x: 2, y: 312, w: 158, h: 173 },
  { codigo: 'P1-05', planta: 'P1', nombre: 'Integración Social 1º', tipo: 'aula', color: '#e07b39',
    grupos: '1º Integración Social', familias: ['SSC'],
    x: 262, y: 133, w: 111, h: 154 },
  { codigo: 'P1-06', planta: 'P1', nombre: 'Integración Social (presencial / semi)', tipo: 'aula', color: '#efbdbd',
    grupos: 'Presencial: 2º G.S. Integración Social\nSemi: 1º Mediación Comunicativa · 1º 2º Integración Social', familias: ['SSC'],
    x: 262, y: 287, w: 111, h: 190 },
  { codigo: 'P1-07', planta: 'P1', nombre: 'Informática 3', tipo: 'informatica', color: '#dcc6dc',
    grupos: 'INFOR 3', familias: ['TIC'],
    x: 450, y: 18, w: 84, h: 122 },
  { codigo: 'P1-08', planta: 'P1', nombre: 'Informática 2', tipo: 'informatica', color: '#e9855f',
    grupos: 'INFOR 2', familias: ['TIC'],
    x: 450, y: 140, w: 84, h: 122 },
  { codigo: 'P1-09', planta: 'P1', nombre: 'Informática 1', tipo: 'informatica', color: '#d4d4d4',
    grupos: 'INFOR 1', familias: ['TIC'],
    x: 450, y: 262, w: 84, h: 135 },
  { codigo: 'P1-10', planta: 'P1', nombre: 'FOL', tipo: 'aula', color: '#f2c94c',
    grupos: 'FOL', familias: [],
    x: 584, y: 20, w: 112, h: 112 },
  { codigo: 'P1-11', planta: 'P1', nombre: 'Acond. Físico 2º / PRL 2º', tipo: 'aula', color: '#efbdbd',
    grupos: '2º G.S. Acondicionamiento Físico\n2º G.S. Prevención de Riesgos Laborales', familias: ['AFD', 'SEA'],
    x: 584, y: 132, w: 112, h: 135 },
  { codigo: 'P1-12', planta: 'P1', nombre: 'Acond. Físico 1º / PRL 1º', tipo: 'aula', color: '#f2b27c',
    grupos: '1º G.S. Acondicionamiento Físico\n1º G.S. Prevención de Riesgos Laborales', familias: ['AFD', 'SEA'],
    x: 584, y: 267, w: 112, h: 138 },
  { codigo: 'P1-13', planta: 'P1', nombre: 'Almacén Ferretería', tipo: 'almacen', color: '#d5e5d0',
    grupos: 'Almacén ferretería', familias: [],
    x: 726, y: 367, w: 112, h: 170 },
  { codigo: 'P1-14', planta: 'P1', nombre: 'Aux. Enfermería 1º / Atención Dependencia 2º', tipo: 'aula', color: '#6ab04c',
    grupos: '1º G.M. Auxiliar de Enfermería\n2º G.M. Atención a Personas en Situación de Dependencia', familias: ['SAN', 'SSC'],
    x: 10, y: 485, w: 205, h: 90 },
  { codigo: 'P1-15', planta: 'P1', nombre: 'Carpintería 1º / Diseño y Amueblamiento 1º', tipo: 'aula', color: '#8cc07a',
    grupos: '1º G.M. Carpintería y Mueble\n1º G.M. Diseño y Amueblamiento', familias: ['MAM'],
    x: 414, y: 473, w: 146, h: 102 },
  { codigo: 'P1-16', planta: 'P1', nombre: 'Animación Sociodeportiva 1º / Recuperación Semi', tipo: 'aula', color: '#6a6fa8',
    grupos: '1º G.S. Animación Sociodeportiva\nRecuperación semi', familias: ['AFD'],
    x: 560, y: 473, w: 142, h: 100 },

  // ── Planta baja ────────────────────────────────────────────────────────
  { codigo: 'PB-01', planta: 'PB', nombre: 'Pastelería', tipo: 'taller', color: '#e07b39',
    grupos: 'Pastelería', familias: ['INA'],
    x: 15, y: 17, w: 152, h: 143 },
  { codigo: 'PB-02', planta: 'PB', nombre: 'Cafetería', tipo: 'taller', color: '#e8d6cc',
    grupos: 'Cafetería\n1º G.B. Panadería y Pastelería\n+21 Restaurante y Bar', familias: ['HOT', 'INA'],
    x: 167, y: 13, w: 209, h: 117 },
  { codigo: 'PB-03', planta: 'PB', nombre: 'Educación Infantil', tipo: 'aula', color: '#f2d91a',
    grupos: '1º C.S. Educación Infantil presencial\n2º C.S. Educación Infantil semi', familias: ['SSC'],
    x: 15, y: 160, w: 155, h: 145 },
  { codigo: 'PB-04', planta: 'PB', nombre: 'Cocina / Psicomotricidad', tipo: 'taller', color: '#b8c7d3',
    grupos: 'Cocina\nPsicomotricidad', familias: ['HOT', 'SSC'],
    x: 18, y: 305, w: 152, h: 163 },
  { codigo: 'PB-05', planta: 'PB', nombre: 'Laboratorio', tipo: 'taller', color: '#c0392b',
    grupos: 'Laboratorio', familias: [],
    x: 267, y: 130, w: 110, h: 145 },
  { codigo: 'PB-06', planta: 'PB', nombre: 'Work Teams', tipo: 'aula', color: '#e3cfc9',
    grupos: 'Work Teams', familias: [],
    x: 270, y: 275, w: 107, h: 178 },
  { codigo: 'PB-07', planta: 'PB', nombre: 'ATECA', tipo: 'informatica', color: '#f0d3e2',
    grupos: 'ATECA', familias: ['TIC'],
    x: 470, y: 108, w: 156, h: 325 },
  { codigo: 'PB-08', planta: 'PB', nombre: '+21', tipo: 'aula', color: '#c9cbd1',
    grupos: '+21', familias: ['HOT'],
    x: 470, y: 108, w: 75, h: 87 },
  { codigo: 'PB-09', planta: 'PB', nombre: 'Plaza', tipo: 'comun', color: null,
    grupos: 'Plaza', familias: [],
    x: 632, y: 110, w: 72, h: 320 },
  { codigo: 'PB-10', planta: 'PB', nombre: 'Taller Carpintería y Mueble', tipo: 'taller', color: '#e9c62e',
    grupos: 'Carpintería y Mueble', familias: ['MAM'],
    x: 712, y: 72, w: 106, h: 108 },
  { codigo: 'PB-11', planta: 'PB', nombre: 'Taller Electricidad / Soldadura', tipo: 'taller', color: '#ecc3c3',
    grupos: 'Electricidad\nSoldadura', familias: ['IMA'],
    x: 712, y: 180, w: 104, h: 160 },
  { codigo: 'PB-12', planta: 'PB', nombre: 'Taller Mecanizado y Soldadura', tipo: 'taller', color: '#c8102e',
    grupos: 'Mecanizado y Soldadura', familias: ['IMA'],
    x: 706, y: 340, w: 106, h: 157 },
];

export const TIPOS_ESPACIO = {
  aula: 'Aula',
  taller: 'Taller',
  informatica: 'Aula de informática',
  almacen: 'Almacén',
  comun: 'Zona común',
};
